### ISSUE TITLE
Empty Response

### ISSUE THREAD

**Issue by RobertDeRose** [zanmato/Add-to-Transmission#1]
I set the setting to my remote transmission client

First Attempt

some.remote.host:9091

UN: username
PW: password

I leave both checkboxes unchecked.

When I click on a link. either Magnet or .torrent, I sometimes get "Empty response"

Second Attempt

http://some.remote.host

same UN and PW

I get An "Unknown Error"

Third Attempt

http://some.remote.host:9091

same UN and PW

This time a Username and Password Prompt appear.  I fill in the UN and PW and get "Unknown Error"

This is using the latest version available as of 8-12-2011

previous version worked, but I wanted the magnet link feature.

**Comment by zanmato** [comment]
Hi,

Make sure that you don't leave out /transmission/rpc, http://some.remote.host:9091/transmission/rpc

**Comment by RobertDeRose** [comment]
Wow... if I would have just not rushed to delete the pre-filled fields, I might have noticed that you included an example.

Thanks... GREAT Safari Extension BTW

**Comment by RobertDeRose** [comment]
Damn... also most works perfectly, except for the fact that it still asks me for my UN and PW when I click

"Add to Transmission"

I've triple checked that the UN and PW are correct in the fields provided.

The work around seems to be to just have safari save the password, but that get reset periodically or if you do a reset in Safari for whatever reason.

Mostly works though.

**Comment by degard66** [comment]
Hello I have a problem because with my settings it simply doesnt work.

I have local address 10.0.0.5 standard port 9091 (http://10.0.0.5:9091/transmission/rpc)
username admin and myprivatepassword

With these settings filled in it does nothing.
What could be wrong?

I use another extension for chrome on my win computer and it works OK with the same settings.

**Comment by zanmato** [comment]
You should be able to browse to that address and get a 409 conflict, does that work?
Also login to the web interface to make sure that the browser isn't remembering the wrong credentials.
