### ISSUE TITLE
Pb with Firefox 19.0.2

### ISSUE THREAD

**Issue by coyotez** [zanmato/Add-to-Transmission#2]
I do not have anymore "add to tramission" menu item and I've got this message in the console  :

Horodatage : 10/03/2013 15:00:30
Erreur : TypeError: menu is null
Fichier Source : chrome://addtotransmission/content/overlay.js
Ligne : 270

Work's fine before. Probably due to lately update of firefox.

**Comment by zanmato** [comment]
It is working for me with the latest version, 19.0.2.
The error suggests that the context menu doesn't exist. Can you list the other extensions you have installed? Or perhaps try disabling them and see if the error still persists.

**Comment by coyotez** [comment]
Absolutly right, it was due to buggy old extension : Orange vidéo.

But the behavior was revealled by the firefox update .....

Thanks a lot !
