### ISSUE TITLE
Torrent link filter needs work

### ISSUE THREAD

**Issue by franciscolourenco** [zanmato/Add-to-Transmission#3]
the torrent link match is not working very well, many torrent links are not being detected

**Comment by zanmato** [comment]
The script cannot know beforehand if it's a torrent unless it ends with .torrent
You can however enable "Enable for all links" in the settings, then it'll work for all links.

**Comment by franciscolourenco** [comment]
Remote Torrent Adder uses regex and works great, so maybe just copy it?
https://chrome.google.com/webstore/detail/remote-torrent-adder/oabphaconndgibllomdcjbfdghcmenci?hl=en

**Comment by franciscolourenco** [comment]
You can see the 2 expressions included by default on the following image:
![img](http://imgur.com/mvrUZ4S.png)

They catch torrents in most of the sites.
