### ISSUE TITLE
[Feature] Download directly without context menu required

### ISSUE THREAD

**Issue by franciscolourenco** [zanmato/Add-to-Transmission#4]
It would great to be able to just click in the torrent links to download them.

**Comment by zanmato** [comment]
I'll look into it!

**Comment by KernelLeak** [comment]
Maybe you could also make your extension handle the "magnet:" URL scheme? I often accidentally click on magnet links, only to get a Firefox warning page saying that the browser doesn't know how to handle that scheme...

**Comment by alexwhitman** [comment]
Came here to request the same feature.

http://mike.kaply.com/2011/01/18/writing-a-firefox-protocol-handler/ describes how to add a protocol handler in Firefox, with http://mike.kaply.com/files/2011/01/twitterProtocolService.js being the interesting code.

**Comment by JoeNyland** [comment]
:+1: for this too: It would be great to just be able to click normally on torrent links and fire them off to Transmission.

**Comment by JoeNyland** [comment]
@KernelLeak I agree that `magnet:` URLs should be used too. I've opened up a new feature request for that here: #8. Hopefully, I can get round to taking a look at it...

**Comment by zanmato** [comment]
I've added support for this today, however you have to package the extension yourselves until I get around to submitting it to Mozilla.

**Comment by JoeNyland** [comment]
As I mentioned in #8, I've just pulled this, then built for Safari and Firefox and I am not seeing the behaviour I expected: In order to download a torrent via both `magnet:` and `.torrent` links, I still have to right-click on the link and click _Add to Transmission_.

If I click normally on a torrent link, I am prompted to choose an app to handle `magnet:` links and the `.torrent` file is downloaded in my browser and not submitted to Transmission.

Do I have to do anything special at the OS level for this to work?

**Comment by zanmato** [comment]
It only works for Firefox, and you have to enable it in the addon settings first (restart required).

**Comment by JoeNyland** [comment]
Indeed, I was mistake, sorry. I suppose I didn't think the string "Handle all downloads" meant that. Maybe needs to say something like "Left-click on torrents to download", but that's just my opinion.

It's a shame this does not work in Safari though, as Safari is my primary browser. Were you able to see if it was possible _at all_ to do this in Safari, when you were working on this?

**Comment by zanmato** [comment]
Yeah, the label is a bit misleading.

Could be possible through a click handler, but it's not a very good solution.

**Comment by JoeNyland** [comment]
Ok, I might take a look at it when I have time, but it's not a big issue, really. Thanks again for your help and also for your time on the extension!
