### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by rosskinard** [zanmato/Add-to-Transmission#5]
Since I download a variety of stuff, it would be nice to be able to assign a Group to the torrent when it gets sent. I separate the download destinations by groups like TV, Movies, Software, Books

Not sure if this is possible, but it would be a really useful function if it is.

Thanks

**Comment by zanmato** [comment]
I agree, unfortunately it is not possible (at least the last time I checked).
The group functionality is not a core feature in transmission, it's more of an "addon" in the OS X version.
(Making it unavailable in their Web API)
