### ISSUE TITLE
Not working with Tixati torret client

### ISSUE THREAD

**Issue by TheArkive** [zanmato/Add-to-Transmission#7]
Here's a link with the recorded network traffic:

https://www.sendspace.com/file/4uy55f

I have a "failed file" that shows attempting with your addon, and i have a "success" file when i submit a magnet/torrent over the web GUI manually.

The files were recorded with WireShark/WinPcap.  If you need another format please let me know.

It would seem that my torrent client of choice is a bit out of the ordinary, although i really hope you might consider adding support for Tixati!

**Comment by TheArkive** [comment]
If you are using WireShark just type in "HTTP" in the filter (no quotes) and you will see all the http traffic.  Sorry I didn't mention that earlier!

**Comment by zanmato** [comment]
Sorry, this extension is only meant for Transmission.
