### ISSUE TITLE
[Feature] Enable detection of magnet: links

### ISSUE THREAD

**Issue by JoeNyland** [zanmato/Add-to-Transmission#8]
As requested by @KernelLeak in #4, I too am looking for support for the `magnet:` URL scheme, too.

I'm going to try and do this myself and create a PR for it, however I can't promise I will be able to find the time to work on this, due to other projects and commitments.

I'm raising this issue here, so that the feature has been formally requested and if anyone gets around to it before me, they are more than happy to pick this up :wink: .

**Comment by zanmato** [comment]
I've added support for this today, however you have to package the extension yourself until I get around to submitting it to Mozilla.

**Comment by JoeNyland** [comment]
That's great - thank you!

I've just built this for Safari (7.0.5) and it's picking up `magnet:` links fine.

**Comment by JoeNyland** [comment]
I've just built for Firefox 31.0 and this feature works there too.
